import type {
  BossBalance,
  BossId,
  DifficultyBalance,
  DifficultyId,
  EnemyArchetypeId,
  EnemyBalance,
  GameModeId,
  ModeBalance,
  PowerUpBalance,
  PowerUpId,
  SectorBalance,
  SectorId,
  UpgradeBalance,
  UpgradeId,
} from "./types.ts";

/** Matches the shared/API/SQL maximum until that contract is migrated. */
export const MAX_RUN_DURATION_MS = 6 * 60 * 60 * 1000;
export const CONTRACT_LEVEL_DURATION_MS = 22_000;
export const MAX_THREAT_LEVEL = 9;
export const MAX_PLANNABLE_WAVES = Math.floor(
  MAX_RUN_DURATION_MS / CONTRACT_LEVEL_DURATION_MS,
);

const ALL_MODES = ["expedition", "survival", "classic"] as const;

export const MODE_BALANCE = {
  expedition: {
    id: "expedition",
    bossInterval: 3,
    finiteWaveCount: 9,
    allowsUpgradeChoices: true,
    sectorCycle: [
      "starfield",
      "nebula",
      "meteor-belt",
      "ice",
      "ion-storm",
      "ship-graveyard",
      "solar",
      "dark",
      "boss",
    ],
    telegraphDurationMs: 2_500,
    combatDurationMs: CONTRACT_LEVEL_DURATION_MS,
    restDurationMs: 6_000,
    threatBase: 7,
    threatGrowth: 3.2,
  },
  survival: {
    id: "survival",
    bossInterval: 3,
    finiteWaveCount: null,
    allowsUpgradeChoices: true,
    sectorCycle: [
      "starfield",
      "nebula",
      "meteor-belt",
      "ice",
      "ion-storm",
      "ship-graveyard",
      "solar",
      "dark",
      "boss",
    ],
    telegraphDurationMs: 1_800,
    combatDurationMs: CONTRACT_LEVEL_DURATION_MS,
    restDurationMs: 4_000,
    threatBase: 8,
    threatGrowth: 3.8,
  },
  classic: {
    id: "classic",
    bossInterval: null,
    finiteWaveCount: null,
    allowsUpgradeChoices: false,
    sectorCycle: ["starfield"],
    telegraphDurationMs: 1_200,
    combatDurationMs: CONTRACT_LEVEL_DURATION_MS,
    restDurationMs: 2_500,
    threatBase: 6,
    threatGrowth: 2.7,
  },
} as const satisfies Record<GameModeId, ModeBalance>;

export const DIFFICULTY_BALANCE = {
  cadet: {
    id: "cadet",
    enemyHealthMultiplier: 0.86,
    enemySpeedMultiplier: 0.86,
    enemyDamageMultiplier: 0.75,
    spawnBudgetMultiplier: 0.82,
    scoreMultiplier: 0.8,
    recoveryDropMultiplier: 1.35,
  },
  pilot: {
    id: "pilot",
    enemyHealthMultiplier: 1,
    enemySpeedMultiplier: 1,
    enemyDamageMultiplier: 1,
    spawnBudgetMultiplier: 1,
    scoreMultiplier: 1,
    recoveryDropMultiplier: 1,
  },
  ace: {
    id: "ace",
    enemyHealthMultiplier: 1.2,
    enemySpeedMultiplier: 1.16,
    enemyDamageMultiplier: 1.25,
    spawnBudgetMultiplier: 1.22,
    scoreMultiplier: 1.5,
    recoveryDropMultiplier: 0.78,
  },
} as const satisfies Record<DifficultyId, DifficultyBalance>;

export const SECTOR_BALANCE = {
  starfield: {
    id: "starfield",
    accent: "#56d7bf",
    backgroundTop: "#071a21",
    backgroundBottom: "#103238",
    particleStyle: "stars",
    hazard: "none",
    musicState: "calm",
    preferredEnemies: ["swift-asteroid", "scout-drone"],
  },
  nebula: {
    id: "nebula",
    accent: "#c58cff",
    backgroundTop: "#180d2b",
    backgroundBottom: "#382450",
    particleStyle: "mist",
    hazard: "visibility-pulse",
    musicState: "drive",
    preferredEnemies: ["hunter-drone", "support-drone"],
  },
  "meteor-belt": {
    id: "meteor-belt",
    accent: "#f2b68d",
    backgroundTop: "#241411",
    backgroundBottom: "#4a2e26",
    particleStyle: "rocks",
    hazard: "debris-lanes",
    musicState: "danger",
    preferredEnemies: [
      "splitter-asteroid",
      "armored-asteroid",
      "debris",
    ],
  },
  ice: {
    id: "ice",
    accent: "#a8e8ff",
    backgroundTop: "#07182d",
    backgroundBottom: "#16445b",
    particleStyle: "crystals",
    hazard: "cryo-drift",
    musicState: "calm",
    preferredEnemies: ["swift-asteroid", "splitter-asteroid"],
  },
  "ion-storm": {
    id: "ion-storm",
    accent: "#9aff6b",
    backgroundTop: "#101b28",
    backgroundBottom: "#274233",
    particleStyle: "ions",
    hazard: "ion-pulse",
    musicState: "danger",
    preferredEnemies: ["gunner-drone", "support-drone"],
  },
  "ship-graveyard": {
    id: "ship-graveyard",
    accent: "#d4b38f",
    backgroundTop: "#15191d",
    backgroundBottom: "#34383b",
    particleStyle: "wreckage",
    hazard: "minefield",
    musicState: "drive",
    preferredEnemies: ["mine", "debris", "hunter-drone"],
  },
  solar: {
    id: "solar",
    accent: "#ffb34f",
    backgroundTop: "#32110b",
    backgroundBottom: "#71311b",
    particleStyle: "embers",
    hazard: "solar-flare",
    musicState: "danger",
    preferredEnemies: ["comet", "armored-asteroid"],
  },
  dark: {
    id: "dark",
    accent: "#8294d8",
    backgroundTop: "#03050c",
    backgroundBottom: "#11162a",
    particleStyle: "shadows",
    hazard: "limited-light",
    musicState: "calm",
    preferredEnemies: ["mine", "hunter-drone", "gunner-drone"],
  },
  boss: {
    id: "boss",
    accent: "#ff6b3d",
    backgroundTop: "#22070a",
    backgroundBottom: "#3b1217",
    particleStyle: "arena",
    hazard: "boss-arena",
    musicState: "boss",
    preferredEnemies: ["support-drone", "gunner-drone"],
  },
} as const satisfies Record<SectorId, SectorBalance>;

export const ENEMY_BALANCE = {
  "swift-asteroid": {
    id: "swift-asteroid",
    unlockWave: 1,
    threatCost: 1,
    selectionWeight: 9,
    baseHealth: 1,
    baseSpeed: 175,
    radius: 15,
    score: 10,
    telegraphMs: 350,
    canBeElite: false,
  },
  "splitter-asteroid": {
    id: "splitter-asteroid",
    unlockWave: 2,
    threatCost: 3,
    selectionWeight: 6,
    baseHealth: 3,
    baseSpeed: 92,
    radius: 34,
    score: 30,
    telegraphMs: 600,
    canBeElite: true,
  },
  "armored-asteroid": {
    id: "armored-asteroid",
    unlockWave: 3,
    threatCost: 4,
    selectionWeight: 4,
    baseHealth: 6,
    baseSpeed: 78,
    radius: 29,
    score: 50,
    telegraphMs: 700,
    canBeElite: true,
  },
  comet: {
    id: "comet",
    unlockWave: 3,
    threatCost: 3,
    selectionWeight: 4,
    baseHealth: 2,
    baseSpeed: 320,
    radius: 18,
    score: 40,
    telegraphMs: 1_000,
    canBeElite: false,
  },
  mine: {
    id: "mine",
    unlockWave: 4,
    threatCost: 3,
    selectionWeight: 4,
    baseHealth: 2,
    baseSpeed: 34,
    radius: 20,
    score: 30,
    telegraphMs: 850,
    canBeElite: true,
  },
  debris: {
    id: "debris",
    unlockWave: 1,
    threatCost: 1,
    selectionWeight: 5,
    baseHealth: 1,
    baseSpeed: 125,
    radius: 13,
    score: 10,
    telegraphMs: 300,
    canBeElite: false,
  },
  "scout-drone": {
    id: "scout-drone",
    unlockWave: 2,
    threatCost: 2,
    selectionWeight: 6,
    baseHealth: 2,
    baseSpeed: 145,
    radius: 18,
    score: 30,
    telegraphMs: 600,
    canBeElite: true,
  },
  "gunner-drone": {
    id: "gunner-drone",
    unlockWave: 4,
    threatCost: 4,
    selectionWeight: 4,
    baseHealth: 4,
    baseSpeed: 94,
    radius: 22,
    score: 50,
    telegraphMs: 900,
    canBeElite: true,
  },
  "hunter-drone": {
    id: "hunter-drone",
    unlockWave: 5,
    threatCost: 4,
    selectionWeight: 4,
    baseHealth: 4,
    baseSpeed: 132,
    radius: 21,
    score: 60,
    telegraphMs: 900,
    canBeElite: true,
  },
  "support-drone": {
    id: "support-drone",
    unlockWave: 6,
    threatCost: 5,
    selectionWeight: 2,
    baseHealth: 5,
    baseSpeed: 76,
    radius: 23,
    score: 70,
    telegraphMs: 1_100,
    canBeElite: false,
  },
} as const satisfies Record<EnemyArchetypeId, EnemyBalance>;

export const BOSS_BALANCE = {
  "sentinel-array": {
    id: "sentinel-array",
    baseHealth: 80,
    score: 500,
    telegraphMs: 1_600,
    phaseThresholds: [0.66, 0.33],
  },
  "comet-leviathan": {
    id: "comet-leviathan",
    baseHealth: 130,
    score: 800,
    telegraphMs: 1_800,
    phaseThresholds: [0.72, 0.38],
  },
  "void-dreadnought": {
    id: "void-dreadnought",
    baseHealth: 190,
    score: 1_200,
    telegraphMs: 2_000,
    phaseThresholds: [0.75, 0.48, 0.22],
  },
} as const satisfies Record<BossId, BossBalance>;

export const UPGRADE_BALANCE = {
  "twin-shot": {
    id: "twin-shot",
    category: "weapon",
    maxStacks: 2,
    selectionWeight: 8,
    compatibleModes: ALL_MODES,
  },
  "rapid-fire": {
    id: "rapid-fire",
    category: "weapon",
    maxStacks: 3,
    selectionWeight: 8,
    compatibleModes: ALL_MODES,
  },
  "piercing-rounds": {
    id: "piercing-rounds",
    category: "weapon",
    maxStacks: 2,
    selectionWeight: 6,
    compatibleModes: ALL_MODES,
  },
  "critical-focus": {
    id: "critical-focus",
    category: "weapon",
    maxStacks: 3,
    selectionWeight: 6,
    compatibleModes: ALL_MODES,
  },
  "reinforced-shield": {
    id: "reinforced-shield",
    category: "defense",
    maxStacks: 3,
    selectionWeight: 8,
    compatibleModes: ALL_MODES,
  },
  "phase-plating": {
    id: "phase-plating",
    category: "defense",
    maxStacks: 2,
    selectionWeight: 6,
    compatibleModes: ALL_MODES,
  },
  "repair-nanites": {
    id: "repair-nanites",
    category: "defense",
    maxStacks: 2,
    selectionWeight: 5,
    compatibleModes: ["expedition", "survival"],
  },
  "engine-boost": {
    id: "engine-boost",
    category: "utility",
    maxStacks: 3,
    selectionWeight: 8,
    compatibleModes: ALL_MODES,
  },
  "missile-bay": {
    id: "missile-bay",
    category: "utility",
    maxStacks: 2,
    selectionWeight: 6,
    compatibleModes: ["expedition", "survival"],
  },
  "emp-capacitor": {
    id: "emp-capacitor",
    category: "utility",
    maxStacks: 3,
    selectionWeight: 6,
    compatibleModes: ["expedition", "survival"],
  },
  "magnet-array": {
    id: "magnet-array",
    category: "utility",
    maxStacks: 2,
    selectionWeight: 7,
    compatibleModes: ["expedition", "survival"],
  },
  "escort-drone": {
    id: "escort-drone",
    category: "utility",
    maxStacks: 2,
    selectionWeight: 5,
    compatibleModes: ["expedition", "survival"],
  },
} as const satisfies Record<UpgradeId, UpgradeBalance>;

export const POWER_UP_BALANCE = {
  shield: {
    id: "shield",
    kind: "temporary",
    durationMs: 10_000,
    cooldownMs: 18_000,
    energyCost: 0,
  },
  spread: {
    id: "spread",
    kind: "temporary",
    durationMs: 9_000,
    cooldownMs: 16_000,
    energyCost: 0,
  },
  laser: {
    id: "laser",
    kind: "active",
    durationMs: 2_600,
    cooldownMs: 18_000,
    energyCost: 65,
  },
  missiles: {
    id: "missiles",
    kind: "active",
    durationMs: 4_500,
    cooldownMs: 20_000,
    energyCost: 55,
  },
  emp: {
    id: "emp",
    kind: "active",
    durationMs: 2_400,
    cooldownMs: 18_000,
    energyCost: 60,
  },
  time: {
    id: "time",
    kind: "active",
    durationMs: 5_000,
    cooldownMs: 24_000,
    energyCost: 70,
  },
  magnet: {
    id: "magnet",
    kind: "temporary",
    durationMs: 12_000,
    cooldownMs: 16_000,
    energyCost: 0,
  },
  drone: {
    id: "drone",
    kind: "temporary",
    durationMs: 14_000,
    cooldownMs: 24_000,
    energyCost: 0,
  },
  repair: {
    id: "repair",
    kind: "instant",
    durationMs: 0,
    cooldownMs: 30_000,
    energyCost: 0,
  },
  pulse: {
    id: "pulse",
    kind: "active",
    durationMs: 1_200,
    cooldownMs: 20_000,
    energyCost: 60,
  },
  invulnerability: {
    id: "invulnerability",
    kind: "active",
    durationMs: 1_800,
    cooldownMs: 26_000,
    energyCost: 75,
  },
  critical: {
    id: "critical",
    kind: "temporary",
    durationMs: 8_000,
    cooldownMs: 18_000,
    energyCost: 0,
  },
  speed: {
    id: "speed",
    kind: "temporary",
    durationMs: 9_000,
    cooldownMs: 16_000,
    energyCost: 0,
  },
  charge: {
    id: "charge",
    kind: "active",
    durationMs: 1_500,
    cooldownMs: 24_000,
    energyCost: 80,
  },
} as const satisfies Record<PowerUpId, PowerUpBalance>;

export function getThreatLevel(activeDurationMs: number) {
  const safeDuration = Math.min(
    MAX_RUN_DURATION_MS,
    Math.max(0, Math.floor(activeDurationMs)),
  );
  return Math.min(
    MAX_THREAT_LEVEL,
    1 + Math.floor(safeDuration / CONTRACT_LEVEL_DURATION_MS),
  );
}

export function getDifficultyScore(baseScore: number, difficulty: DifficultyId) {
  const score = baseScore * DIFFICULTY_BALANCE[difficulty].scoreMultiplier;
  return Math.max(0, Math.round(score / 10) * 10);
}
